# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65e01f218696374ae5c309e193788773f6b6e62034f648d43eab2195ef323273967ccae4f54032518e21eca53696ba8e10eab59de12191555a3e3666649ac5b6

test:
  secret_key_base: e20ad7cd69ed334781bcff4c870d962b869e48eeca97dac7fb6fba689e1981ceea12bb3ce0aa74cf6f76253a991cfe4bd1a877da01f9d34ef0f22f78cd536ed0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
